### ISSUE TITLE
Infinite loop in randomiseDB function from basefunction.js

### ISSUE THREAD

**Issue by ankitsatapara07** [Eleven-am/nino-pub#1]
Hi,
I have found one scenario in which the function runs for infinite time in the basefunction.js.
This eventually stops all the operations.

```
while (array.some(file => file.tmdb_id === this[int].tmdb_id) || this[int].tmdb_id === id || this[int].type === type)
                int = Math.floor(Math.random() * this.length);
```

**My case:**
Array have nothing in it,  so first condition will become false,
I have one record in DB having same tmdb id so second will be true and also I have same type so it will also becomes true.

hence, no way to quit for the while loop so it becomes infinite.

Please let me know if more inputs are required.

Thanks,
Ankit

**Comment by eleven-am** [comment]
Hey I'd appreciate more context as I can't seem to trace the bug you're referring to. This while loop only runs if the array applying the prototype has elements in it.
`if (this.length) `
Also the moment any condition in the loop becomes false the loop is broken so if the tray within the prototype is empty, like when I initialise it, `array.some(file => file.tmdb_id === this[int].tmdb_id)` would fail, breaking the loop.

So yeah please, more context might be needed to understand the problem

**Comment by eleven-am** [comment]
I think just found the bug. if the array calling the prototype has only item in it. it would loop if the item is also the id /type to be rejected. 

Thanks for this. I would update the code but leave the issue open until I get a verification that on your end it's fixed

**Comment by ankitsatapara07** [comment]
Thanks for spending your time and fix it.
It is working as expected now.
:)
